# Generated by Django 2.2.10 on 2021-05-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant_skill',
            name='batchid',
            field=models.BigIntegerField(default=0),
        ),
    ]
